services:
  - type: web
    name: event-trigger-platform
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:create_app()
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SQLALCHEMY_DATABASE_URI
        value: postgresql://event_trigger_db_user:QZDwB0qVV33h0QPvHR11KbED7zIWfiBT@dpg-cv96ip52ng1s73d0mfcg-a.oregon-postgres.render.com/event_trigger_db