"""Initial migration

Revision ID: 725918e6982b
Revises: 
Create Date: 2025-03-13 12:02:53.877888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '725918e6982b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trigger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trigger_id', sa.Integer(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('is_test', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['trigger_id'], ['trigger.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_log')
    op.drop_table('trigger')
    # ### end Alembic commands ###
